name: Release Version

# Manual or automatic release
on:
  release:
    types: [ published ]

jobs:
  build_win:
    runs-on: windows-latest
    strategy:
        matrix:
          architecture: [x86, x64]
    name: Windows ${{ matrix.architecture }} Build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.0"
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: |
          pip install -r ronnia/requirements.txt
      - name: Install build dependencies
        run: |
          pip install -r ronnia/requirements_build.txt
      - name: Build ${{ matrix.architecture }}
        run: |
          pyinstaller ronnia.spec --noconfirm

      - name: Copy config.ini
        run: cp config.ini dist/

      - name: Update Release
        uses: ncipollo/release-action@v1.9.0
        with:
          artifacts: ronnia_win_${{ matrix.architecture }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: ${{ github.event.release.tag_name }}
          body: |
            <details>
              <summary>Release Notes</summary>
              <p>
                ${{ github.event.release.body }}
              </p>
            </details>
